### ISSUE TITLE
how to show an indicator (bullet) when not using thumbnails

### ISSUE THREAD

**Issue by maku** [lukasz-galka/ngx-gallery#123]
Im my use case I don't want to show thumbnails but I would like to have some kind of indicator which shows how many images are in the gallery (eg. bullets ->  also with navigation capabilities)

Is this possible with ngx-gallery?

TIA

**Comment by lukasz-galka** [comment]
Hi @maku, unfortunately no.

**Comment by lukasz-galka** [comment]
I've added `imageBullets` and `previewBullets` in `5.8.0`

**Comment by dv0c** [comment]
> I've added `imageBullets` and `previewBullets` in `5.8.0`

Everytime i add imageBullets into my code i get this error

core.mjs:6485 ERROR TypeError: Cannot read properties of undefined (reading 'length')
    at NgxGalleryImageComponent_ngx_gallery_bullets_2_Template (kolkov-ngx-gallery.mjs:875:3285)
    at executeTemplate (core.mjs:9618:1)
    at refreshView (core.mjs:9484:1)
    at refreshEmbeddedViews (core.mjs:10609:1)
    at refreshView (core.mjs:9508:1)
    at refreshComponent (core.mjs:10655:1)
    at refreshChildComponents (core.mjs:9280:1)
    at refreshView (core.mjs:9534:1)
    at refreshEmbeddedViews (core.mjs:10609:1)
    at refreshView (core.mjs:9508:1)
