### ISSUE TITLE
AOT

### ISSUE THREAD

**Issue by csysmans** [lukasz-galka/ngx-gallery#16]
Hi!

Very nice library and it works great in my application.
However when I try to build my webpack application with AOT, I receive the following message:

`
Module not found: Error: Can't resolve 'ngx-gallery/ngx-gallery.module' in '/Users/christophe/Projects/find-out/platform/src/www/.tmp/app'
    at factoryCallback (/Users/christophe/Projects/find-out/platform/node_modules/webpack/lib/Compilation.js:264:39)
    at factory (/Users/christophe/Projects/find-out/platform/node_modules/webpack/lib/NormalModuleFactory.js:247:20)
    at resolver (/Users/christophe/Projects/find-out/platform/node_modules/webpack/lib/NormalModuleFactory.js:65:21)
    at asyncLib.parallel.e (/Users/christophe/Projects/find-out/platform/node_modules/webpack/lib/NormalModuleFactory.js:138:21)
    at /Users/christophe/Projects/find-out/platform/node_modules/async/dist/async.js:3861:9
    at /Users/christophe/Projects/find-out/platform/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/christophe/Projects/find-out/platform/node_modules/async/dist/async.js:996:13)
    at /Users/christophe/Projects/find-out/platform/node_modules/async/dist/async.js:906:16
    at /Users/christophe/Projects/find-out/platform/node_modules/async/dist/async.js:3858:13
    at resolvers.normal.resolve (/Users/christophe/Projects/find-out/platform/node_modules/webpack/lib/NormalModuleFactory.js:130:23)
    at onError (/Users/christophe/Projects/find-out/platform/node_modules/enhanced-resolve/lib/Resolver.js:65:10)
    at loggingCallbackWrapper (/Users/christophe/Projects/find-out/platform/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/christophe/Projects/find-out/platform/node_modules/enhanced-resolve/lib/Resolver.js:146:10)
    at loggingCallbackWrapper (/Users/christophe/Projects/find-out/platform/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/christophe/Projects/find-out/platform/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/Users/christophe/Projects/find-out/platform/node_modules/enhanced-resolve/lib/Resolver.js:133:19)
    at loggingCallbackWrapper (/Users/christophe/Projects/find-out/platform/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/christophe/Projects/find-out/platform/node_modules/tapable/lib/Tapable.js:283:15
    at /Users/christophe/Projects/find-out/platform/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (/Users/christophe/Projects/find-out/platform/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/christophe/Projects/find-out/platform/node_modules/enhanced-resolve/lib/Resolver.js:146:10)
    at loggingCallbackWrapper (/Users/christophe/Projects/find-out/platform/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/christophe/Projects/find-out/platform/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/Users/christophe/Projects/find-out/platform/node_modules/enhanced-resolve/lib/Resolver.js:133:19)
    at loggingCallbackWrapper (/Users/christophe/Projects/find-out/platform/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/christophe/Projects/find-out/platform/node_modules/tapable/lib/Tapable.js:283:15
    at innerCallback (/Users/christophe/Projects/find-out/platform/node_modules/enhanced-resolve/lib/Resolver.js:131:11)
    at loggingCallbackWrapper (/Users/christophe/Projects/find-out/platform/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/christophe/Projects/find-out/platform/node_modules/tapable/lib/Tapable.js:283:15
    at resolver.doResolve.createInnerCallback (/Users/christophe/Projects/find-out/platform/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
resolve 'ngx-gallery/ngx-gallery.module' in '/Users/christophe/Projects/find-out/platform/src/www/.tmp/app'
  Parsed request is a module
  using description file: /Users/christophe/Projects/find-out/platform/package.json (relative path: ./src/www/.tmp/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/christophe/Projects/find-out/platform/package.json (relative path: ./src/www/.tmp/app)
    resolve as module
      looking for modules in /Users/christophe/Projects/find-out/platform/node_modules
        using description file: /Users/christophe/Projects/find-out/platform/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/christophe/Projects/find-out/platform/package.json (relative path: ./node_modules)
          using description file: /Users/christophe/Projects/find-out/platform/node_modules/ngx-gallery/package.json (relative path: ./ngx-gallery.module)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/christophe/Projects/find-out/platform/node_modules/ngx-gallery/ngx-gallery.module doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/christophe/Projects/find-out/platform/node_modules/ngx-gallery/ngx-gallery.module.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/christophe/Projects/find-out/platform/node_modules/ngx-gallery/ngx-gallery.module.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/christophe/Projects/find-out/platform/node_modules/ngx-gallery/ngx-gallery.module.json doesn't exist
            as directory
              /Users/christophe/Projects/find-out/platform/node_modules/ngx-gallery/ngx-gallery.module doesn't exist
      looking for modules in /Users/christophe/Projects/find-out/platform/node_modules/node_modules
        using description file: /Users/christophe/Projects/find-out/platform/package.json (relative path: ./node_modules/node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/christophe/Projects/find-out/platform/package.json (relative path: ./node_modules/node_modules)
          using description file: /Users/christophe/Projects/find-out/platform/package.json (relative path: ./node_modules/node_modules/ngx-gallery/ngx-gallery.module)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/christophe/Projects/find-out/platform/node_modules/node_modules/ngx-gallery/ngx-gallery.module doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/christophe/Projects/find-out/platform/node_modules/node_modules/ngx-gallery/ngx-gallery.module.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/christophe/Projects/find-out/platform/node_modules/node_modules/ngx-gallery/ngx-gallery.module.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/christophe/Projects/find-out/platform/node_modules/node_modules/ngx-gallery/ngx-gallery.module.json doesn't exist
            as directory
              /Users/christophe/Projects/find-out/platform/node_modules/node_modules/ngx-gallery/ngx-gallery.module doesn't exist
      looking for modules in /Users/christophe/Projects/find-out/platform/src/www
        using description file: /Users/christophe/Projects/find-out/platform/package.json (relative path: ./src/www)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/christophe/Projects/find-out/platform/package.json (relative path: ./src/www)
          using description file: /Users/christophe/Projects/find-out/platform/package.json (relative path: ./src/www/ngx-gallery/ngx-gallery.module)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/christophe/Projects/find-out/platform/src/www/ngx-gallery/ngx-gallery.module doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/christophe/Projects/find-out/platform/src/www/ngx-gallery/ngx-gallery.module.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/christophe/Projects/find-out/platform/src/www/ngx-gallery/ngx-gallery.module.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/christophe/Projects/find-out/platform/src/www/ngx-gallery/ngx-gallery.module.json doesn't exist
            as directory
              /Users/christophe/Projects/find-out/platform/src/www/ngx-gallery/ngx-gallery.module doesn't exist
`

Has this module been tested with AOT?  Without AOT (but still with webpack) it works without a problem.

**Comment by lukasz-galka** [comment]
Hi, AOT is broken in version 1.0.0 (I'm working on fix), so at this moment please use version 0.8.5
npm i -S ngx-gallery@0.8.5

**Comment by csysmans** [comment]
Works like a charm! Thanks.
