### ISSUE TITLE
Setting for closing full-image preview by clicking on black wrapper

### ISSUE THREAD

**Issue by arkhamvm** [lukasz-galka/ngx-gallery#2]
Hello, thanks for awesome plugin!
I need to closing preview by clicking on preview wrapper, is there a setting to do this?

**Comment by lukasz-galka** [comment]
Hi, I have added option 'previewCloseOnClick' in version 0.7.2

**Comment by arkhamvm** [comment]
Great, thanks!
But looks like error here:
```
Can't bind to 'closeOnClick' since it isn't a known property of 'ngx-gallery-preview'.
```

Full stack:
```
1. If 'ngx-gallery-preview' is an Angular component and it has 'closeOnClick' input, then verify that it is part of this module.
2. If 'ngx-gallery-preview' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("wDescription" [swipe]="currentOptions.previewSwipe" [fullscreen]="currentOptions.previewFullscreen" [ERROR ->][closeOnClick]="currentOptions.previewCloseOnClick" (onClose)="onClosePreview()" [class.ngx-gallery-a"): ng:///NgxGalleryModule/NgxGalleryComponent.html@4:212 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:(…) Error: Template parse errors:
Can't bind to 'closeOnClick' since it isn't a known property of 'ngx-gallery-preview'.
1. If 'ngx-gallery-preview' is an Angular component and it has 'closeOnClick' input, then verify that it is part of this module.
2. If 'ngx-gallery-preview' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("wDescription" [swipe]="currentOptions.previewSwipe" [fullscreen]="currentOptions.previewFullscreen" [ERROR ->][closeOnClick]="currentOptions.previewCloseOnClick" (onClose)="onClosePreview()" [class.ngx-gallery-a"): ng:///NgxGalleryModule/NgxGalleryComponent.html@4:212
    at syntaxError (http://localhost:3000/vendor.bundle.js:68953:34) [<root>]
    at TemplateParser.parse (http://localhost:3000/vendor.bundle.js:78962:19) [<root>]
    at JitCompiler._compileTemplate (http://localhost:3000/vendor.bundle.js:92736:39) [<root>]
    at http://localhost:3000/vendor.bundle.js:92660:62 [<root>]
    at Set.forEach (native) [<root>]
    at JitCompiler._compileComponents (http://localhost:3000/vendor.bundle.js:92660:19) [<root>]
    at createResult (http://localhost:3000/vendor.bundle.js:92545:19) [<root>]
    at Zone.run (http://localhost:3000/polyfills.bundle.js:2925:43) [<root> => <root>]
    at http://localhost:3000/polyfills.bundle.js:3560:57 [<root>]
    at Zone.runTask (http://localhost:3000/polyfills.bundle.js:2965:47) [<root> => <root>]
    at drainMicroTaskQueue (http://localhost:3000/polyfills.bundle.js:3393:35) [<root>]consoleError @ zone.js:569handleUnhandledRejection @ zone.js:574_loop_1 @ zone.js:609drainMicroTaskQueue @ zone.js:613
zone.js:571 Error: Uncaught (in promise): Error: Template parse errors:(…)consoleError @ zone.js:571handleUnhandledRejection @ zone.js:574_loop_1 @ zone.js:609drainMicroTaskQueue @ zone.js:613
```
