### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by NicoUnlimited** [lukasz-galka/ngx-gallery#220]
Hey guys,

Got a problem since updating to Angular5.

Using ng serve I got following errors 

ERROR in ./node_modules/ngx-gallery/lib/ngx-gallery-animation.model.ts
Module build failed: Error: /Users/NicoHermann/Desktop/Arbeit/RSK/node_modules/ngx-gallery/lib/ngx-gallery-animation.model.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/NicoHermann/Desktop/Arbeit/RSK/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/Users/NicoHermann/Desktop/Arbeit/RSK/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)
ERROR in ./node_modules/ngx-gallery/lib/ngx-gallery-image-size.model.ts
Module build failed: Error: /Users/NicoHermann/Desktop/Arbeit/RSK/node_modules/ngx-gallery/lib/ngx-gallery-image-size.model.ts is missing from the TypeScript compilation. Please makesure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/NicoHermann/Desktop/Arbeit/RSK/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/Users/NicoHermann/Desktop/Arbeit/RSK/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)
ERROR in ./node_modules/ngx-gallery/lib/ngx-gallery-image.model.ts
Module build failed: Error: /Users/NicoHermann/Desktop/Arbeit/RSK/node_modules/ngx-gallery/lib/ngx-gallery-image.model.ts is missing from the TypeScript compilation. Please make sureit is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/NicoHermann/Desktop/Arbeit/RSK/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/Users/NicoHermann/Desktop/Arbeit/RSK/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)
ERROR in ./node_modules/ngx-gallery/lib/ngx-gallery-layout.model.ts
Module build failed: Error: /Users/NicoHermann/Desktop/Arbeit/RSK/node_modules/ngx-gallery/lib/ngx-gallery-layout.model.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/NicoHermann/Desktop/Arbeit/RSK/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/Users/NicoHermann/Desktop/Arbeit/RSK/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)
ERROR in ./node_modules/ngx-gallery/lib/ngx-gallery-options.model.ts
Module build failed: Error: /Users/NicoHermann/Desktop/Arbeit/RSK/node_modules/ngx-gallery/lib/ngx-gallery-options.model.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/NicoHermann/Desktop/Arbeit/RSK/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/Users/NicoHermann/Desktop/Arbeit/RSK/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)
ERROR in ./node_modules/ngx-gallery/lib/ngx-gallery.component.ts
Module build failed: Error: /Users/NicoHermann/Desktop/Arbeit/RSK/node_modules/ngx-gallery/lib/ngx-gallery.component.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/NicoHermann/Desktop/Arbeit/RSK/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/Users/NicoHermann/Desktop/Arbeit/RSK/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)
ERROR in ./node_modules/ngx-gallery/lib/ngx-gallery.module.ts
Module build failed: Error: /Users/NicoHermann/Desktop/Arbeit/RSK/node_modules/ngx-gallery/lib/ngx-gallery.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/NicoHermann/Desktop/Arbeit/RSK/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/Users/NicoHermann/Desktop/Arbeit/RSK/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)

System : 

Angular CLI: 1.7.4
Node: 6.10.0
OS: darwin x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.4.2
webpack: 3.11.0

Any Ideas for this one?

**Comment by NicoUnlimited** [comment]
Just a problem with my version of ngx-gallery. Close here.
