### ISSUE TITLE
Can't resolve all parameters for NgxGalleryComponen

### ISSUE THREAD

**Issue by Gotemperor** [lukasz-galka/ngx-gallery#57]
Hi, I am using angular2 and file upload from ng2-file-upload and I am trying to implement your gallery, but I get an error in the console.
Can you please help me? What can cost this error?

SyntaxError {__zone_symbol__error: Error: Can't resolve all parameters for NgxGalleryComponent: ([object Object], ?).
    at SyntaxErro…, …}message: (...)name: (...)originalStack: (...)stack: (...)toSource: ƒ ()toString: ƒ ()zoneAwareStack: (...)__zone_symbol__error: Error: Can't resolve all parameters for NgxGalleryComponent: ([object Object], ?).
    at SyntaxError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:7009:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:31905:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:51727:16)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/src/metadata_resolver.js.CompileMetadataResolver._getDependenciesMetadata (http://localhost:4200/vendor.bundle.js:37970:31)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/src/metadata_resolver.js.CompileMetadataResolver._getTypeMetadata (http://localhost:4200/vendor.bundle.js:37845:26)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/src/metadata_resolver.js.CompileMetadataResolver.getNonNormalizedDirectiveMetadata (http://localhost:4200/vendor.bundle.js:37485:24)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/src/metadata_resolver.js.CompileMetadataResolver._loadDirectiveMetadata (http://localhost:4200/vendor.bundle.js:37361:23)
    at http://localhost:4200/vendor.bundle.js:37562:54
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/src/metadata_resolver.js.CompileMetadataResolver.loadNgModuleDirectiveAndPipeMetadata (http://localhost:4200/vendor.bundle.js:37561:41)
    at http://localhost:4200/vendor.bundle.js:36435:58
    at Array.forEach (<anonymous>)
    at JitCompiler.webpackJsonp.../../../compiler/src/jit/compiler.js.JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:36434:43)
    at JitCompiler.webpackJsonp.../../../compiler/src/jit/compiler.js.JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:36389:52)
    at JitCompiler.webpackJsonp.../../../compiler/src/jit/compiler.js.JitCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:36355:21)_nativeError: ZoneAwareError {__zone_symbol__error: Error: Can't resolve all parameters for NgxGalleryComponent: ([object Object], ?).
    at SyntaxErro…, …}get message: ƒ ()set message: ƒ (value)get name: ƒ ()set name: ƒ (value)get originalStack: ƒ ()set originalStack: ƒ (value)get stack: ƒ ()set stack: ƒ (value)get zoneAwareStack: ƒ ()set zoneAwareStack: ƒ (value)__proto__: BaseError
webpackJsonp.../../../compiler/src/metadata_resolver.js.CompileMetadataResolver._reportError @ metadata_resolver.js:972
webpackJsonp.../../../compiler/src/metadata_resolver.js.CompileMetadataResolver._getDependenciesMetadata @ metadata_resolver.js:784
webpackJsonp.../../../compiler/src/metadata_resolver.js.CompileMetadataResolver._getTypeMetadata @ metadata_resolver.js:659
webpackJsonp.../../../compiler/src/metadata_resolver.js.CompileMetadataResolver.getNonNormalizedDirectiveMetadata @ metadata_resolver.js:299
webpackJsonp.../../../compiler/src/metadata_resolver.js.CompileMetadataResolver._loadDirectiveMetadata @ metadata_resolver.js:175
(anonymous) @ metadata_resolver.js:376
webpackJsonp.../../../compiler/src/metadata_resolver.js.CompileMetadataResolver.loadNgModuleDirectiveAndPipeMetadata @ metadata_resolver.js:375
(anonymous) @ compiler.js:171
webpackJsonp.../../../compiler/src/jit/compiler.js.JitCompiler._loadModules @ compiler.js:170
webpackJsonp.../../../compiler/src/jit/compiler.js.JitCompiler._compileModuleAndComponents @ compiler.js:125
webpackJsonp.../../../compiler/src/jit/compiler.js.JitCompiler.compileModuleAsync @ compiler.js:91
webpackJsonp.../../../core/src/application_ref.js.PlatformRef_._bootstrapModuleWithZone @ application_ref.js:390
webpackJsonp.../../../core/src/application_ref.js.PlatformRef_.bootstrapModule @ application_ref.js:365
../../../../../src/main.ts @ main.ts:10
__webpack_require__ @ bootstrap 2d8e54f29cbb6cbc1cb7:54
0 @ main.bundle.js:274
__webpack_require__ @ bootstrap 2d8e54f29cbb6cbc1cb7:54
webpackJsonpCallback @ bootstrap 2d8e54f29cbb6cbc1cb7:25
(anonymous) @ main.bundle.js:1

**Comment by lukasz-galka** [comment]
Hi @Gotemperor, cosntructor for `NgxGalleryComponent` loks like https://github.com/lukasz-galka/ngx-gallery/blob/master/src/ngx-gallery.component.ts#L61 

There is probably problem with `PLATFORM_ID`, I will read about it and let you know.

If you are using angular cli please show my output from `ng -v` (from your project directory), if not please show `package.json`

**Comment by lukasz-galka** [comment]
@Gotemperor, please check version `2.4.1`
